### ISSUE TITLE
避免被玩家滥用的几种方案

### ISSUE THREAD

**Issue by 272416939** [kkj9333/IVshop-core#1]
1、固定摊位费

2、按照物品价格按比例收钱上架费用

3、超过多少价格后开始按比例收取上架费用（如低于100不收钱，超过100收取10%（配置文件修改））

个人觉得方案3更好

**Comment by kkj9333** [comment]
以上方案如果上架后修改价格则无意义，
执行方案4：
玩家上架超过x个物品后，之后上架的每个槽位收取额外固定费用

**Comment by kkj9333** [comment]
1.0.9.4已解决

**Comment by kkj9333** [comment]
1.0.9.4已解决
