### ISSUE TITLE
店铺封禁功能

### ISSUE THREAD

**Issue by 272416939** [kkj9333/IVshop-core#2]
添加封禁玩家店铺功能，封禁后不能上架物品（出售、回收），只能对已上架物品进行下架，已上架物品不能被搜索到也不能被发现
分为永久封禁和限时封禁，并通知玩家封禁的原因

**Comment by kkj9333** [comment]
已处理

**Comment by kkj9333** [comment]
大概1.0.9会更新此功能

**Comment by kkj9333** [comment]
1.0.9.4已解决
