### ISSUE TITLE
无法正常购买商品

### ISSUE THREAD

**Issue by zyy82** [kkj9333/IVshop-core#6]
当玩家点击购买商品，UI没有任何东西可点击
控制台报错:[Inventoryshop] An error was caught during the update process.
使用1.0.9.4版本出现的问题

**Comment by kkj9333** [comment]
已着手修复，应该是1.0.9.4不兼容旧数据的原因。

**Comment by rtucc** [comment]
我也遇到了这个问题
也是报错

**Comment by kkj9333** [comment]
能否提供一下data文件数据 需要旧数据测试

**Comment by rtucc** [comment]
[data.zip](https://github.com/kkj9333/IVshop-core/files/9413300/data.zip)

**Comment by kkj9333** [comment]
应该修复了

**Comment by kkj9333** [comment]
请下载1.0.9.7
