### ISSUE TITLE
上架有蜜蜂的蜂巢与美西螈桶服务器关闭

### ISSUE THREAD

**Issue by rtucc** [kkj9333/IVshop-core#7]
如题
玩家上架美西螈桶与带有蜜蜂蜂巢时
输出The file xuid.json is NULL,try load default json...
然后服务器关闭
并且之前的上架的物品都没了
版本1.0.11

**Comment by kkj9333** [comment]
![image](https://user-images.githubusercontent.com/51207072/190848445-f13d8b69-f27f-4b76-9651-712dec71ee8c.png)
无法复现

**Comment by kkj9333** [comment]
问题已解决
