### ISSUE TITLE
把这些加进语言文件

### ISSUE THREAD

**Issue by lanbosq** [kkj9333/IVshop-core#8]
### 操作系统

Windows 11

### LiteLoader版本

最新

### BDS版本

1.19.51

### ivshop版本

最新

### 发生了什么?

把这几个
mainmenu
sellmenu
sell
recycle
都加进语言文件里

### 复现此问题的步骤

无

### 有关的日志/输出

```shell
无
```

**Comment by kkj9333** [comment]
已添加，你可以试试
[beta](https://github.com/kkj9333/IVshop-core/releases/tag/beta)

**Comment by kkj9333** [comment]
会在下次更新时正式加入
